### ISSUE TITLE
Load Config

### ISSUE THREAD

**Issue by ndeto** [punkhazardlabs/txpool-viz#2]
Parse the yaml file and initialize the project

```yaml
endpoints:
- name: "geth-1"
url: "http://localhost:8545/"
auth_headers: {} # Optional auth headers
- name: "erigon-1"
url: "http://localhost:8547/"
polling:
interval: "5s" # How often to poll mempools
timeout: "2s" # RPC timeout
filters:
min_gas_price: "1gwei" # Optional filters
```
